name: dispatch getsentry bump-sentry

on:
  push:
#    branches:
#      - master

jobs:
  dispatch:
    name: dispatch
    runs-on: ubuntu-20.04
    steps:
      - name: Dispatch getsentry tests
        uses: actions/github-script@v6
        with:
          # This Personal Access Token belongs to getsentry-bot,
          # who can write to getsentry and is SAML+SSO ready.
          github-token: ${{ secrets.BUMP_SENTRY_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'getsentry',
              repo: 'getsentry-test-repo',
              workflow_id: 'bump-sentry.yml',
              ref: 'master',
              inputs: '{ "sentry_sha": "${{ github.sha }}" '
            })
